#!/bin/sh

COMPOSE_HOME=${COMPOSE_HOME:-/docker}

COMMAND=$1

while [ "$#" -gt 0 ]; do
    case "$1" in
        -*)
            ARGS="$ARGS $1"
            ;;
        *)
            PROJECT_NAME="$1"
            ;;
    esac
    shift
done

case $COMMAND in
	"ls")
		ls "${COMPOSE_HOME}"
		exit 0
	;;

	"full-restart")
		docker compose --project-directory "${COMPOSE_HOME}/${PROJECT_NAME}" down
		docker compose --project-directory "${COMPOSE_HOME}/${PROJECT_NAME}" up -d
		exit 0
	;;

	"*") ;;
esac

echo docker compose --project-directory "${COMPOSE_HOME}/${PROJECT_NAME}" $COMMAND $ARGS
